project:
  type: website

website:
  title: "Datatunes"
  site-url: https://mj-datatunes.com
  navbar:
    right:
      - text: About
        href: index.qmd
      - text: Blog
        href: blog.qmd
      - text: CV
        href: cv.qmd
      - icon: github
        href: https://github.com/
      
        
google-analytics: G-L00JHD3B47
cookie-consent: true

format:
  html:
    theme: yeti
    

editor: visual

