project:
  type: website

website:
  title: "Mj website"
  navbar:
    right:
      - text: About
        href: index.qmd
      - text: Blog
        href: blog.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

